name: URaffle
favicon: null
layout_spectrum: 0.91947
typography_spectrum: 0.68624
title: U Raffle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7dd28'
    - '#6aa016'
    - '#e6e4f1'
    - '#181822'
    - '#c17ea1'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
