name: URaffle
favicon: null
layout_spectrum: 0
typography_spectrum: 0.68624
title: U Raffle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7dd28'
    - '#6aa016'
    - '#e6e4f1'
    - '#181822'
    - '#c17ea1'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
